/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 Component Pack 4
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <SW2_aliases.h>
#include <SW2.h>
#include <Debounce_Clock.h>
#include <Pin_12_4_aliases.h>
#include <Pin_12_4.h>
#include <SW3_aliases.h>
#include <SW3.h>
#include <SCL_EZI2C_aliases.h>
#include <SCL_EZI2C.h>
#include <Pin_12_7_aliases.h>
#include <Pin_12_7.h>
#include <SDA_EZI2C_aliases.h>
#include <SDA_EZI2C.h>
#include <EZI2C.h>
#include <LED3_aliases.h>
#include <LED3.h>
#include <LED4_aliases.h>
#include <LED4.h>
#include <LCD.h>
#include <LCD_LCDPort_aliases.h>
#include <LCD_LCDPort.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
